import Footer from "@/components/layouts/Footer";
import Header from "@/components/layouts/Header";
import MainMenu from "@/components/layouts/MainMenu";
import "bootstrap/dist/css/bootstrap.min.css";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <MainMenu />
        {children}
        <Footer />
      </body>
    </html>
  );
}
